- name: example playbook
  hosts: localhost
  vars:
    http_port: 80
    https_port: 443
    
    packages:
      -git
      -mysql-client
      -curl
      -wget
      
    appserver:
      hostname: webapp01
      ipaddress: 192.168.1.202
      os: windows server 2019

  tasks:
    - name: display the single variables
      debug:
        var: http_port, https_port
        
    - name: display the list of variables
      debug:
        var: packages   
        
    - name: display dictionary variables
      debug:
        var: appserver   