---
# tasks file for roles/webserver

- name: Installing Apache
  yum:
    name: httpd
    state: present
    
- name: Stating Apache
  service:
    name: httpd
    state: started
    enabled: true

- name: Copy Files
  copy: src=devops-process.png dest=/var/www/html
  
- name: Generate Template
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
  notify:
    - Restarting Apache